name: JMeter Performance Test


on:
  workflow_dispatch:  # Allows manual triggering only
    inputs:
      script_name:
        description: 'Script name to execute'
        required: true
        type: string
        default: 'test-script.js'
      duration:
        description: 'Test duration (e.g., 30s, 5m, 1h)'
        required: true
        type: string
        default: '5'
      rampup:
        description: 'Ramp-up time (e.g., 10s, 1m, 2m)'
        required: true
        type: string
        default: '1'
      user_count:
        description: 'Number of users to simulate'
        required: true
        type: string
        default: '1'
jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xvf apache-jmeter-5.6.2.tgz
        
    - name: Run JMeter Test
      run: |
        apache-jmeter-5.6.2/bin/jmeter -n -t ${{ inputs.script_name }} \
          -Jduration=${{ inputs.duration }} \
          -Jrampup=${{ inputs.rampup }} \
          -Juser_count=${{ inputs.user_count }} \
          -l test-results.jtl \
          -e -o html-report

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jmeter-test-results
        path: |
          test-results.jtl
          html-report/