name: JMeter Docker Performance Test


on:
  push:
    branches: [ main ]
    default:
      script_name: 'UI_Script.jmx'
      duration: '5'
      rampup: '1'
      user_count: '1'
  pull_request:
    branches: [ main ]
    default:
      script_name: 'UI_Script.jmx'
      duration: '5'
      rampup: '1'
      user_count: '1'
  workflow_dispatch:  # Allows manual triggering only
    inputs:
    # this should be drop down menu
      script_name:
        type: dropdown
        description: 'Script name to execute'
        required: true
        options:
          - UI_Script.jmx
          - json-project.jmx
        type: string
        default: 'UI_Script.jmx'
      duration:
        description: 'Test duration (e.g., 30s, 5m, 1h)'
        required: true
        type: string
        default: '5'
      rampup:
        description: 'Ramp-up time (e.g., 10s, 1m, 2m)'
        required: true
        type: string
        default: '1'
      user_count:
        description: 'Number of users to simulate'
        required: true
        type: string
        default: '1'
jobs:
  docker-jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create output directories
      run: |
        mkdir -p jmeter/results
        mkdir -p jmeter/reports

    - name: Run JMeter Test in Docker
      run: |
        docker run --rm \
          -v "${PWD}:/jmeter" \
          -w /jmeter \
          justb4/jmeter:5.5 \
          -n \
          -t ${{ inputs.script_name }} \
          -Dduration=${{ inputs.duration }} \
          -Drampup=${{ inputs.rampup }} \
          -Duser_count=${{ inputs.user_count }} \
          -l jmeter/results/test-results.jtl \
          -e \
          -o jmeter/reports/html-report

    - name: Upload JMeter Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-docker-results
        path: |
          jmeter/results/*.jtl
          jmeter/reports/html-report/

    - name: Check Test Results
      run: |
        if grep -q "false" jmeter/results/test-results.jtl; then
          echo "Test failures found in JMeter results"
          exit 1
        else
          echo "All tests passed successfully"
        fi