name: JMeter Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xvf apache-jmeter-5.6.2.tgz
        
    - name: Run JMeter Test
      run: |
        apache-jmeter-5.6.2/bin/jmeter -n -t json-project.jmx \
          -l test-results.jtl \
          -e -o html-report

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jmeter-test-results
        path: |
          test-results.jtl
          html-report/